using ACE.Entity.Enum;
using ACE.Server.Network.GameMessages;
using Org.BouncyCastle.Tls;
using System;
using System.Reflection.Emit;
using System.Security.Policy;

namespace ACE.Server.Entity.Actions
{
    public enum ActionType : int
    {
        AdminCommands_HandleActionQueryHouse,
        AdvocateFane_Bestow,
        AdvocateFane_Reset,
        Aetheria_ActivateSigil,
        AllegianceManager_DoHandlePlayerDelete,
        AllegianceManager_DoPassXP,
        Bindstone_EnqueueBroadcastMotion,
        Bindstone_SetSanctuary,
        Chest_Reset,
        ConfirmationManager_EnqueueAbort,
        Container_FinishClose,
        Container_Reset,
        Container_SortBiotasIntoInventory,
        Corpse_DiscoverGeneratedRare,
        CreatureDeath_MakeCorpse,
        CreatureDeath_SaveInParallelCallback,
        CreatureEquipment_TryActivateItemSpellsOnWield,
        CreatureMissile_EnqueueBroadcast,
        CreatureMissile_EnsureAmmoVisible,
        CreatureNavigation_AddMoveToTick,
        CreatureNavigation_Rotate,
        CreatureNavigation_TurnToPosition,
        CreatureNavigation_TurnToTarget,
        CreatureNetworking_DoWorldBroadcast,
        Door_FinalizeClose,
        Door_Reset,
        Door_SetNotBusy,
        EmoteManager_CastSpell,
        EmoteManager_DebugDelay,
        EmoteManager_DoEnqueue,
        EmoteManager_ExecuteMotion,
        EmoteManager_Give,
        EmoteManager_OnDamage,
        EmoteManager_ReduceNested,
        Enlightenment_DoEnlighten,
        Game_GameOverCleanup,
        Game_GameOverStats,
        GamePiece_ApplyDeadVisuals,
        GamePiece_Destroy,
        GamePiece_EnqueueDeadMotion,
        Healer_DoHealing,
        Healer_SendMotion,
        Hotspot_ActionLoop,
        HouseManager_HandlePlayerDelete,
        Landblock_ClearFlagsAfterSave,
        Landblock_CreateWorldObjects,
        Landblock_Init,
        Landblock_SpawnDynamicShardObjects,
        Landblock_SpawnEncounters,
        Landblock_TeleportPlayerAfterFailureToAdd,
        Lifestone_EnqueueSound,
        Lifestone_Use,
        Lock_UseUnlocker,
        MonsterAwareness_CheckTargetsInner,
        MonsterCombat_DeleteObjectAfterDelay,
        MonsterMagic_CastSpell,
        MonsterMelee_DoAttack,
        MonsterMissile_EnqueueBroadcast,
        MonsterMissile_LaunchMissile,
        MonsterMissile_LaunchMissileInner,
        MonsterMissile_SetStance,
        MonsterMissile_SwitchToMeleeAttack,
        MonsterMissile_SwitchToMeleeAttackInner,
        MonsterMissile_SwitchToMeleeAttackInnerInner,
        MonsterNavigation_Sleep,
        PetDevice_Refill,
        PhysicsObj_TrackObject,
        PhysicsObj_TrackObjects,
        PKModifier_EnqueueDissonanceAndReset,
        PKModifier_TogglePKStauts,
        Player_FinalizeLogout,
        Player_ForceLogOff,
        Player_PKLiteSetState,
        Player_PKLiteStartTransition,
        Player_SendNonCombatStance,
        Player_SetNonBusy,
        PlayerAllegiance_HandleLogin,
        PlayerDatabase_SaveBiotasInParallelCallback,
        PlayerCombat_ChangeCombatMode,
        PlayerCombat_ChangeCombatModeCallback,
        PlayerCombat_SetActionType,
        PlayerCombat_SetCombatMode,
        PlayerDeath_Broadcast,
        PlayerDeath_CreateCorpseAndTeleport,
        PlayerDeath_EnqueueTeleport,
        PlayerDeath_HandleSuicide,
        PlayerDeath_Teleport,
        PlayerHouse_HandleActionQueryHouse,
        PlayerHouse_HandleEvictionOnLogin,
        PlayerHouse_NotificationsOnLogin,
        PlayerHouse_SetHouseDataOnOwnerChange,
        PlayerLocation_ClearFogColor,
        PlayerLocation_DoPreTeleportHide,
        PlayerLocation_OnTeleportComplete,
        PlayerLocation_TeleportToAllegianceHometown,
        PlayerLocation_TeleportToAllegianceMansion,
        PlayerLocation_TeleportToHouse,
        PlayerLocation_TeleportToLifestone,
        PlayerLocation_TeleportToMarketplace,
        PlayerLocation_TeleportToPKArena,
        PlayerLocation_TeleportToPKLArena,
        PlayerLocation_TeleToPosition,
        PlayerInventory_AddObjectToLandblock,
        PlayerInventory_DoPickup,
        PlayerInventory_DropItem,
        PlayerInventory_GetAndWieldInventory,
        PlayerInventory_GiveObjectToPlayer,
        PlayerInventory_RemoveTrackedObject,
        PlayerInventory_SetPickupDone,
        PlayerInventory_StackableMerge,
        PlayerInventory_StackableSplitToContainer,
        PlayerInventory_StackableSplitToLandblock,
        PlayerInventory_StackableSplitToWield,
        PlayerMagic_DoCastSpell,
        PlayerMagic_DoCastSpellOnMotionDone,
        PlayerMagic_FastTick,
        PlayerMagic_FinishCast,
        PlayerMagic_OnMoveComplete,
        PlayerMagic_RecordCast,
        PlayerMagic_ReturnToReadyStance,
        PlayerMagic_StartCastingGesture,
        PlayerManager_HandleDeletePlayer,
        PlayerManager_ProcessDeletedPlayer,
        PlayerMelee_Attack,
        PlayerMelee_AttackInner,
        PlayerMelee_HandleTargetedAttack,
        PlayerMelee_PowerbarRefill,
        PlayerMissile_LaunchMissile,
        PlayerMissile_LaunchProjectile,
        PlayerMissile_OutOfAmmo,
        PlayerMissile_PlaceNewAmmo,
        PlayerMissile_PowerbarRefill,
        PlayerMissile_SetAttacking,
        PlayerMotion_SendMotionAsCommands,
        PlayerMove_MoveToChain,
        PlayerMove_MoveToTick,
        PlayerMove_SetLastMoveAndCallCallback,
        PlayerNetworking_EnqueueSend,
        PlayerNetworking_SendShutdownMessage,
        PlayerSkills_HandleActionRaiseSkill,
        PlayerSkills_SendFreeAttributeResetRenewedMessage,
        PlayerSkills_SendFreeResetRenewedMessage,
        PlayerSkills_SendInstallDirtyFightingPatchesMessage,
        PlayerSkills_SendInstallSummoningPatchesMessage,
        PlayerSkills_SendInstallVoidMagicPatchesMessage,
        PlayerSkills_SendMasteriesResetRenewedMessage,
        PlayerSkills_SendSkillTemplesResetMessage,
        PlayerSkills_SendSpecializedSkillResetMessage,
        PlayerSkills_SendTrainedSkillResetMessage,
        PlayerSpells_HandleMaxVitalUpdate,
        PlayerTick_RemoveSpellsOnItemManaDepleted,
        PlayerTracking_CloakStep1,
        PlayerTracking_CloakStep2,
        PlayerTracking_CloakStep3,
        PlayerTracking_CloakStep4,
        PlayerTracking_DeCloakStep1,
        PlayerTracking_DeCloakStep2,
        PlayerTracking_DeCloakStep3,
        PlayerTracking_DeCloakStep4,
        PlayerTrade_EnqueueSendAddToTrade,
        PlayerTrade_FinalizeTrade,
        PlayerUse_ApplyConsumableAction,
        PlayerUse_SendUseDoneEvent,
        PlayerUse_SetNonBusy,
        PlayerXp_HandleMissingXp,
        PlayerXp_ItemIncreasedInPower,
        PlayerXp_RemoveVitae,
        PlayerXp_UpdateXpAndLevel,
        PlayerXp_FlushBatchedUpdate,
        Portal_Teleport,
        RecipeManager_FinishRecipe,
        RecipeManager_HandleRecipe,
        RecipeManager_ShowDialogue,
        Scroll_Read,
        SpellProjectile_Destroy,
        Switch_BaseOnActivate,
        Tailoring_DoTailoring,
        Vendor_ApplyService,
        Vendor_Approach,
        Vendor_CheckClose,
        Vendor_LoadInventory,
        Vendor_SetNotBusy,
        WorldManager_DisconnectAllSessions,
        WorldManager_DoPlayerEnterWorld,
        WorldManager_LogOffAllPlayers,
        WorldManager_PlayerEnterWorld,
        WorldManager_ThreadSafeTeleport,
        WorldObject_Destroy,
        WorldObjectDecay_Destroy,
        WorldObjectMagic_AdjustDungeonAndTeleportPlayer,
        WorldObjectMagic_TryProcCloakSpell,
        WorldObjectNetworking_BroadcastOther,
        WorldObjectNetworking_BroadcastSelf,
        WorldObjectNetworking_EnqueueMotion,
        WorldObjectNetworking_EnqueueMotionForce,
        WorldObjectNetworking_EnqueueMotionMagic,
        WorldObjectNetworking_EnqueueMotionMagicAction,
        WorldObjectNetworking_EnqueueMotionMagicPersist,
        WorldObjectNetworking_EnqueueMotionMissile,
        WorldObjectNetworking_EnqueueMotionMissilePersist,

        // GameMessage values map 1:1 with networking OpTypes.
        GameMessage_Unknown,
        GameMessage_None,
        GameMessage_InventoryRemoveObject,
        GameMessage_SetStackSize,
        GameMessage_PlayerKilled,
        GameMessage_EmoteText,
        GameMessage_SoulEmote,
        GameMessage_HearSpeech,
        GameMessage_HearRangedSpeech,
        GameMessage_PrivateUpdatePropertyInt,
        GameMessage_PublicUpdatePropertyInt,
        GameMessage_PrivateUpdatePropertyInt64,
        GameMessage_PublicUpdatePropertyInt64,
        GameMessage_PrivateUpdatePropertyBool,
        GameMessage_PublicUpdatePropertyBool,
        GameMessage_PrivateUpdatePropertyFloat,
        GameMessage_PublicUpdatePropertyFloat,
        GameMessage_PrivateUpdatePropertyString,
        GameMessage_PublicUpdatePropertyString,
        GameMessage_PrivateUpdatePropertyDataID,
        GameMessage_PublicUpdatePropertyDataID,
        GameMessage_PrivateUpdatePropertyInstanceID,
        GameMessage_PublicUpdateInstanceId,
        GameMessage_PrivateUpdatePosition,
        GameMessage_PublicUpdatePosition,
        GameMessage_PrivateUpdateSkill,
        GameMessage_PublicUpdateSkill,
        GameMessage_PrivateUpdateSkillLevel,
        GameMessage_PublicUpdateSkillLevel,
        GameMessage_PrivateUpdateAttribute,
        GameMessage_PublicUpdateAttribute,
        GameMessage_PrivateUpdateVital,
        GameMessage_PublicUpdateVital,
        GameMessage_PrivateUpdateAttribute2ndLevel,
        GameMessage_AdminEnvirons,
        GameMessage_PositionAndMovement,
        GameMessage_ObjDescEvent,
        GameMessage_CharacterCreateOrRestoreResponse,
        GameMessage_CharacterLogOff,
        GameMessage_CharacterDelete,
        GameMessage_CharacterCreate,
        GameMessage_CharacterEnterWorld,
        GameMessage_CharacterList,
        GameMessage_CharacterError,
        GameMessage_ForceObjectDescSend,
        GameMessage_ObjectCreate,
        GameMessage_PlayerCreate,
        GameMessage_ObjectDelete,
        GameMessage_UpdatePosition,
        GameMessage_ParentEvent,
        GameMessage_PickupEvent,
        GameMessage_SetState,
        GameMessage_MovementEvent,
        GameMessage_VectorUpdate,
        GameMessage_Sound,
        GameMessage_PlayerTeleport,
        GameMessage_AutonomousPosition,
        GameMessage_PlayScriptId,
        GameMessage_PlayEffect,
        GameMessage_GameEvent,
        GameMessage_GameAction,
        GameMessage_AccountBanned,
        GameMessage_CharacterEnterWorldRequest,
        GameMessage_GetServerVersion,
        GameMessage_FriendsOld,
        GameMessage_CharacterRestore,
        GameMessage_AccountBoot,
        GameMessage_UpdateObject,
        GameMessage_TurbineChat,
        GameMessage_CharacterEnterWorldServerReady,
        GameMessage_ServerMessage,
        GameMessage_ServerName,
        GameMessage_DDD_DataMessage,
        GameMessage_DDD_RequestDataMessage,
        GameMessage_DDD_ErrorMessage,
        GameMessage_DDD_Interrogation,
        GameMessage_DDD_InterrogationResponse,
        GameMessage_DDD_BeginDDD,
        GameMessage_DDD_BeginPullDDD,
        GameMessage_DDD_IterationData,
        GameMessage_DDD_EndDDD,

        // These purely exist for control flow / classes.
        ControlFlowLoop,
        ControlFlowConditional,
        ControlFlowDelay,
    }
    public static class ActionTypeConverter
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public static ActionType FromInboundGameMessageOpCode(InboundGameMessageOpcode opcode)
        {
            switch (opcode)
            {
                case InboundGameMessageOpcode.None: return ActionType.GameMessage_None;
                case InboundGameMessageOpcode.ForceObjectDescSend: return ActionType.GameMessage_ForceObjectDescSend;
                case InboundGameMessageOpcode.GameAction: return ActionType.GameMessage_GameAction;
                case InboundGameMessageOpcode.GetServerVersion: return ActionType.GameMessage_GetServerVersion;
                case InboundGameMessageOpcode.FriendsOld: return ActionType.GameMessage_FriendsOld;
                case InboundGameMessageOpcode.TurbineChat: return ActionType.GameMessage_TurbineChat;
                case InboundGameMessageOpcode.CharacterLogOff: return ActionType.GameMessage_CharacterLogOff;
                case InboundGameMessageOpcode.CharacterDelete: return ActionType.GameMessage_CharacterDelete;
                case InboundGameMessageOpcode.CharacterCreate: return ActionType.GameMessage_CharacterCreate;
                case InboundGameMessageOpcode.CharacterEnterWorld: return ActionType.GameMessage_CharacterEnterWorld;
                case InboundGameMessageOpcode.CharacterEnterWorldRequest: return ActionType.GameMessage_CharacterEnterWorldRequest;
                case InboundGameMessageOpcode.CharacterRestore: return ActionType.GameMessage_CharacterRestore;
                case InboundGameMessageOpcode.DDD_InterrogationResponse: return ActionType.GameMessage_DDD_InterrogationResponse;
                case InboundGameMessageOpcode.DDD_RequestDataMessage: return ActionType.GameMessage_DDD_RequestDataMessage;
                case InboundGameMessageOpcode.DDD_EndDDD: return ActionType.GameMessage_DDD_EndDDD;
            }
            log.Warn($"Unknown InboundGameMessageOpCode detected: 0x{((int)opcode):X4}:{opcode}");
            return ActionType.GameMessage_Unknown;
        }
    }

    public interface IAction
    {
        ActionType Type { get; }

        Tuple<IActor, IAction> Act();

        void RunOnFinish(IActor actor, IAction action);
    }
}
