USE `ace_auth`;

CREATE TABLE IF NOT EXISTS `portal_page_access` (
  `page_key` VARCHAR(64) NOT NULL,
  `min_level` TINYINT UNSIGNED NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`page_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
